import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Basic's Logo</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo.png' />
      </Head>
      <main className='logo'>
        <img src='/logo.png' alt="Basic's School" height='50%' />
        <h1>Basic&apos;s School</h1>
      </main>
    </div>
  );
}
